---
## Facts
- name: Set Stack Name
  ansible.builtin.set_fact:
    stack_name: edgerouter

- name: "{{ stack_name }}: Set Stack Folder"
  ansible.builtin.set_fact:
    stack_folder: "/opt/{{ stack_name }}"

- name: "{{ stack_name }}: Set Stack Volume Folder"
  ansible.builtin.set_fact:
    stack_volume_folder: "{{ stack_folder }}/volumes"

- name: Clone Repo
  git:
    repo: https://github.com/Mind-Hochschul-Netzwerk/traefik.git
    dest: "{{ stack_folder }}"

# Ensure Folders
- name: "{{ stack_name }}: Create Folders"
  ansible.builtin.file:
    path: "{{ item }}/"
    state: directory
  loop:
    - "{{ stack_volume_folder }}/traefik/acme/"
    - "{{ stack_volume_folder }}/traefik/config/"
    - "{{ stack_volume_folder }}/traefik/logs/"

- name: "{{ stack_name }}: Template docker .env"
  ansible.builtin.template:
    src: "traefik.env.j2"
    dest: "{{ stack_folder }}/.env"

## Deploy Stack
- name: "{{ stack_name }}: Create and start Stack"
  community.general.docker_compose:
    state: present
    project_name: "{{ stack_name }}"
    project_src: "{{ stack_folder }}"
    files:
      - docker-compose.base.yml
      - docker-compose.dev.yml
