---
- name: Provision Server
  become: true # Run as Root
  hosts: all
  roles:
    - base
    - lockdown
    - edgerouter
    - mailu
    - ldap
    - account
    - moodle
    - mitglieder
    - aufnahme
    - pretix
