---
- name: Provision Server
  hosts: all
  roles:
    # Base Roles:
    - role: dockerbase
      become: true # Run as Root
      tags:
        - base
    - role: lockdown
      become: true # Run as Root
      tags:
        - lockdown

    # Docker Stacks:
    - traefik
    - mailu
    - ldap
    - moodle
    - mitglieder
    - aufnahme
    - pretix
