---
- name: Provision Initial User
  hosts: all
  gather_facts: no
  become: true
  roles:
    - maybecreateuser # gather_facts must be disabled here to use this role

- name: Provision Servers
  hosts: all
  roles:
    # Base Roles:
    - role: dockerbase
      become: true # Run as Root
      tags:
        - base
    - role: lockdown
      become: true # Run as Root
      tags:
        - lockdown

    - role: borgbackup
      become: true # Run as Root
      tags:
        - backup

    # Docker Stacks:
    - traefik
    - mailu
    - ldap
    - moodle
    - mitglieder
    - aufnahme
    - pretix
