---
- name: Provision Server
  hosts: all
  roles:
    - role: base
      become: true # Run as Root
      tags:
        - base
    - role: lockdown
      become: true # Run as Root
      tags:
        - lockdown
    - traefik
    - mailu
    - ldap
    # - account
    - moodle
    - mitglieder
    - aufnahme
    - pretix
