---
- name: Provision Initial User
  hosts: all
  gather_facts: no
  roles:
    - joshkreud.initialuser # gather_facts must be disabled here to use this role
  tags: ["init"]

- name: Provision Servers
  hosts: all
  roles:
    # Base Roles:
    - role: base
      tags: ["base"]
    - role: lockdown
      tags: ["lockdown"]
    - role: docker
      tags: ["docker"]
    - role: borgbackup
      tags: ["backup"]

- name: Deploy Docker Stacks
  hosts: all
  become: no
  roles:
    # Docker Stacks:
    - php-base
    - role: traefik
      tags: ["traefik"]
    - role: mailu
      tags: ["mailu"]
    - role: ldap
    - role: moodle
    - role: mitglieder
    - role: aufnahme
    - role: pretix
    - role: akademie
    - role: referenten
    - role: wiki
