---
- name: Provision Initial User
  hosts: all
  gather_facts: no
  roles:
    - initialuser # gather_facts must be disabled here to use this role

- name: Provision Servers
  hosts: all
  roles:
    # Base Roles:
    - role: base
      tags: ["base"]
    - role: lockdown
      tags: ["lockdown"]
    - role: fail2ban
      tags: ["fail2ban"]
    - role: docker
      tags: ["docker"]
    - role: borgbackup
      tags: ["backup"]

- name: Deploy Docker Stacks
  hosts: all
  become: no
  roles:
    # Docker Stacks:
    - php-base
    - role: traefik
      tags: ["traefik"]
    - mailu
    - ldap
    - moodle
    - mitglieder
    - aufnahme
    - pretix
    - akademie
    - referenten
    - wiki
  tags:
    - dockerstacks
