---
- name: Provision Initial User
  hosts: all
  gather_facts: no
  roles:
    - initialuser # gather_facts must be disabled here to use this role

- name: Provision Servers
  hosts: all
  become: true
  roles:
    # Base Roles:
    - role: dockerbase
      tags:
        - base
    - role: lockdown
      tags:
        - lockdown
    - role: borgbackup
      tags:
        - backup

- name: Deploy Docker Stacks
  hosts: all
  become: no
  roles:
    # Docker Stacks:
    - php-base
    - traefik
    - mailu
    - ldap
    - moodle
    - mitglieder
    - aufnahme
    - pretix
    - akademie
    - referenten
    - wiki
  tags:
    - dockerstacks
