- name: "Set Stack Name"
  ansible.builtin.set_fact:
    stack_name: "mailu"

- name: "Set Stack Folder"
  ansible.builtin.set_fact:
    stack_folder: "/opt/{{ stack_name }}"

- name: "Set Stack Volume Folder"
  ansible.builtin.set_fact:
    stack_volume_folder: "/srv/{{ stack_name }}"

- name: "Ensure Stack Folder exists"
  become: true
  ansible.builtin.file:
    path: "{{ stack_folder }}/"
    state: directory
    owner: "{{ ansible_user }}"

- name: Clone Repo
  git:
    repo: https://github.com/Mind-Hochschul-Netzwerk/mailu.git
    dest: "{{ stack_folder }}"
    version: "{{ mailu_branch }}"

# Ensure Folders
- name: "Create Folders"
  become: true
  ansible.builtin.file:
    path: "{{ item }}/"
    state: directory
  loop:
    - "{{ stack_volume_folder }}/redis/"
    - "{{ stack_volume_folder }}/certs/"
    - "{{ stack_volume_folder }}/overrides/"
    - "{{ stack_volume_folder }}/data/"
    - "{{ stack_volume_folder }}/dkim/"
    - "{{ stack_volume_folder }}/mail/"
    - "{{ stack_volume_folder }}/filter/"
  tags:
    - stackvolumes

- name: "Template mailu .env"
  ansible.builtin.template:
    src: "mailu.env.j2"
    dest: "{{ stack_folder }}/mailu.env"

- name: "Template docker .env"
  become: true
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ stack_folder }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

## Deploy Stack
- name: Deploy Stack
  community.general.make:
    chdir: "{{ stack_folder }}"
    target: "{{ mailu_make_target }}"
  tags:
    - startstack
