---
- name: restart ssh
  service:
    name: sshd
    state: restarted

- name: restart ufw
  community.general.ufw:
    state: reloaded

- name: Restart fail2ban
  service:
    name: "fail2ban"
    state: "restarted"
