---
- name: Set timezone
  community.general.timezone:
    name: "{{ time_zone }}"

- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname  }}"

- name: packages | ensure apt list dir exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755

- name: Update all packages to their latest version
  apt:
    name: "*"
    update_cache: yes
    cache_valid_time: 600
    state: latest
  tags:
    - never
    - update

- name: Install Packages
  ansible.builtin.package:
    name:
      - git
      - build-essential
    state: latest

- name: ensure Pip Packages installed
  import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: jsondiff
      - name: pyyaml

- name: ensure Docker Installed
  import_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: no #causes timeout in gerlingguy role

- name: add a vm.overcommit_memory setting at the end of the sysctl.conf #For Redis
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present
    reload: yes

- name: Make Bashcompletion on case insensitive
  become: yes
  lineinfile:
    path: /etc/inputrc
    regexp: "^set completion-ignore-case"
    line: set completion-ignore-case On

- name: Set Max journal log size
  become: yes
  lineinfile:
    path: /etc/systemd/journald.conf
    line: SystemMaxUse=200M
  notify: restart journald

- name: Include Users
  include_tasks: users.yml
  when: deploy_users is defined
  tags:
    - users

- name: Flush handlers
  meta: flush_handlers

- name: reset ssh connection # To enforce group changes
  meta: reset_connection
