---
- name: Install the latest version of Borgbackup
  ansible.builtin.package:
    name:
      - borgbackup
    state: latest

- name: Template Backup Script
  ansible.builtin.template:
    src: borg-backup.j2
    dest: /usr/local/sbin/borg-backup

- name: Template Prune Script
  ansible.builtin.template:
    src: borg-prune.j2
    dest: /usr/local/sbin/borg-prune

- name: Add Borg Ssh PrivKey
  ansible.builtin.copy:
    path: /root/.ssh/id_borg
    content: "{{ borg_backup_ssh_key }}"

- name: Set Backup Cron Job
  ansible.builtin.cron:
    name: "Borg Backup"
    minute: "47"
    hour: "4"
    job: "/usr/local/sbin/borg-backup"

- name: Set Backup Prune Cron Job
  ansible.builtin.cron:
    name: "Borg Prune"
    minute: "37"
    hour: "2"
    job: "/usr/local/sbin/borg-prune"
