---
- name: Install the latest version of Borgbackup
  ansible.builtin.package:
    name:
      - borgbackup
      - jq
    state: latest

- name: Add Borg Ssh PrivKey
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/.ssh/id_borg"
    content: "{{ borg_backup_ssh_key }}"
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0600

- name: ensure Pip Packages installed
  import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: borgmatic

- name: Borgmatic Config Folder
  become: true
  ansible.builtin.file:
    path: "/etc/borgmatic"
    state: directory
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0770

- name: Template Borgmatic Config
  ansible.builtin.template:
    src: borgmatic-config.yaml.j2
    dest: /etc/borgmatic/config.yaml
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0660

- name: Template Database Dump Script
  ansible.builtin.template:
    src: "dump-databases.j2"
    dest: "/usr/local/sbin/dump-databases"
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0770

- name: Template Mysql Restore helper Script
  ansible.builtin.template:
    src: "restore-mysql.j2"
    dest: "/usr/local/sbin/restore-mysql"
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0770

- name: Template Postgres Restore helper Script
  ansible.builtin.template:
    src: "restore-postgres.j2"
    dest: "/usr/local/sbin/restore-postgres"
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0770

- name: Set Backup Cron Job
  ansible.builtin.cron:
    name: "Borg Backup"
    minute: "47"
    hour: "4"
    job: "PATH=$PATH:/usr/bin:/usr/local/bin borgmatic --syslog-verbosity 1"
  tags:
    - backupcron
