---
- name: Install the latest version of Borgbackup
  ansible.builtin.package:
    name:
      - borgbackup
    state: latest

- name: Borg Config Folder
  become: true
  ansible.builtin.file:
    path: "/etc/borg"
    state: directory

- name: Template Borg Config
  ansible.builtin.template:
    src: borg-config.j2
    dest: /etc/borg/config
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0660

- name: Template Borg Scripts
  ansible.builtin.template:
    src: borg-{{ item }}.j2
    dest: /usr/local/sbin/borg-{{ item }}
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0770
  loop:
    - check
    - init
    - backup
    - prune
    - list

- name: Template Restore Script
  ansible.builtin.template:
    src: borg-restore-latest.py.j2
    dest: /usr/local/sbin/borg-restore-latest
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0770

- name: Add Borg Ssh PrivKey
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/.ssh/id_borg"
    content: "{{ borg_backup_ssh_key }}"
    owner: "{{ ansible_user }}"
    group: "root"
    mode: 0600
# - name: Set Backup Cron Job
#   ansible.builtin.cron:
#     name: "Borg Backup"
#     minute: "47"
#     hour: "4"
#     job: "/usr/local/sbin/borg-backup --cron"

# - name: Set Backup Prune Cron Job
#   ansible.builtin.cron:
#     name: "Borg Prune"
#     minute: "37"
#     hour: "2"
#     job: "/usr/local/sbin/borg-prune --cron"
