---
- name: Install the latest version of Borgbackup
  ansible.builtin.package:
    name:
      - borgbackup
    state: latest

- name: Template Borg Config
  ansible.builtin.template:
    src: borg-config.j2
    dest: /etc/borg/config
    mode: 0600

- name: Template Borg Scripts
  ansible.builtin.template:
    src: borg-{{ item }}.j2
    dest: /usr/local/sbin/borg-{{ item }}
  loop:
    - check
    - init
    - backup
    - prune
    - list

- name: Template Restore Script
  ansible.builtin.template:
    src: borg-restore-latest.py.j2
    dest: /usr/local/sbin/borg-restore-latest

- name: Add Borg Ssh PrivKey
  ansible.builtin.copy:
    path: /root/.ssh/id_borg
    content: "{{ borg_backup_ssh_key }}"
    mode: 0600
# - name: Set Backup Cron Job
#   ansible.builtin.cron:
#     name: "Borg Backup"
#     minute: "47"
#     hour: "4"
#     job: "/usr/local/sbin/borg-backup --cron"

# - name: Set Backup Prune Cron Job
#   ansible.builtin.cron:
#     name: "Borg Prune"
#     minute: "37"
#     hour: "2"
#     job: "/usr/local/sbin/borg-prune --cron"
