- name: Install Fail2Ban
  become: yes
  ansible.builtin.apt:
    name: fail2ban
    update_cache: yes
    state: present

- name: Enable Fail2Ban
  become: yes
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: yes
