---
- name: Install Ufw
  package:
    name: ufw
    state: latest

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled

- name: Set SSH limiting in UFW
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  notify: restart ufw

- name: Allow TCP Ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "587"
    - "110"
    - "143"
    - "80"
    - "465"
    - "25"
    - "443"
    - "993"
    - "995"
    - "49153"
  notify: restart ufw

- name: Deny Other Ports
  community.general.ufw:
    policy: deny
  notify: restart ufw
