- name: Install docker Fail2Ban Action
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/action.d/docker-action.conf
    owner: root
    group: root
    mode: 0600
    content: |
      [Definition]

      actionstart = iptables -N f2b-bad-auth
                    iptables -A f2b-bad-auth -j RETURN
                    iptables -I DOCKER-USER -p tcp -m multiport --dports 1:1024 -j f2b-bad-auth

      actionstop = iptables -D DOCKER-USER -p tcp -m multiport --dports 1:1024 -j f2b-bad-auth
                  iptables -F f2b-bad-auth
                  iptables -X f2b-bad-auth

      actioncheck = iptables -n -L DOCKER-USER | grep -q 'f2b-bad-auth[ \t]'

      actionban = iptables -I f2b-bad-auth 1 -s <ip> -j DROP

      actionunban = iptables -D f2b-bad-auth -s <ip> -j DROP

- name: Create a Fail2ban Service override directory
  become: yes
  file:
    owner: root
    group: root
    mode: 0755
    path: /etc/systemd/system/fail2ban.service.d
    state: directory

- name: Set up fail2ban.service override
  become: yes
  ini_file:
    dest: /etc/systemd/system/fail2ban.service.d/docker_override.conf
    owner: root
    group: root
    create: true
    mode: 0644
    section: Unit
    option: After
    value: docker.service
  notify: Restart fail2ban
