---
- name: Install Apparmor
  become: yes
  ansible.builtin.apt:
    name: apparmor
    state: present

- name: Install Docker
  become: yes
  ansible.builtin.import_role:
    name: geerlingguy.docker

- name: Limit Docker Logs
  become: yes
  ansible.builtin.copy:
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "5m",
          "max-file": "2"
        }
      }
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644

- name: Docker Fail2Ban
  ansible.builtin.include_tasks: fail2ban.yml
  tags: ["fail2ban"]
