---
- name: Set timezone
  community.general.timezone:
    name: "{{ time_zone }}"

- name: Make Bashcompletion on anible user case insensitive
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/inputrc
    regexp: "^set completion-ignore-case"
    line: set completion-ignore-case On

- name: Add a vm.overcommit_memory setting at the end of the sysctl.conf # For Redis
  become: yes
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present
    reload: yes

- name: Packages | ensure apt list dir exists
  become: yes
  ansible.builtin.file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755

- name: Install Packages
  become: yes
  ansible.builtin.package:
    name:
      - git
      - build-essential
    state: latest

- name: Set Max journal log size
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    line: SystemMaxUse=200M
  notify: Restart journald
