---
- name: Updating hostname (1/2) {{ hostname }}
  when: hostname is defined
  become: yes
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  notify: Reboot System

- name: Updating hostname (2/2) {{ hostname }}
  when: hostname is defined
  become: yes
  ansible.builtin.copy:
    content: "{{ hostname }}{{'\n'}}"
    dest: /etc/hostname
    backup: true
    mode: 0644
    owner: root
  notify: Reboot System

- name: Update /etc/hosts
  when: hostname is defined
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1    {{ hostname }}"
    backup: true
    state: present
  notify: Reboot System

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
