---
- name: Set Hostname
  ansible.builtin.include_tasks: hostname.yml

- name: Set Hostname
  ansible.builtin.include_tasks: basic-setup.yml

- name: Ensure Pip Packages installed
  ansible.builtin.import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: jsondiff
      - name: pyyaml

- name: Include Users
  ansible.builtin.include_tasks: users.yml
  when: deploy_users is defined
  tags:
    - users

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Reset ssh connection # To enforce group changes
  ansible.builtin.meta: reset_connection
